services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:14.11
    ports:
      - 5432:5432
    env_file:
      - ./docker/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: public.ecr.aws/docker/library/redis:6.2.16
    ports:
      - 6379:6379

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025

  refund_request_processing_system:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - 8000:8000
    env_file:
    - ./docker/.env
    volumes:
      - ./refund_request_processing_system:/app/refund_request_processing_system
    command: python refund_request_processing_system/manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: