services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:14.11
    ports:
      - 5432:5432
    env_file:
      - ./docker/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  refund_request_processing_system:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - 8000:8000
    env_file:
    - ./docker/.env
    volumes:
      - ./refund_request_processing_system:/app/refund_request_processing_system
    command: echo "Please implement the container command!"
    depends_on:
      - postgres

volumes:
  postgres_data: