# Generated by Django 5.1.7 on 2025-03-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0002_refundrequeststatuschangeemailmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refundrequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
